# Task 1: Get and prepare the data
### In this task, I will write code that reads the content of all files combining all data together in a single dataframe.

In [26]:
import pandas as pd

## For 2010

In [27]:
read_file = pd.read_csv ('yob/yob2010.txt')
read_file.to_csv('yob/2010.csv', index=None)
df = pd.read_csv("yob/2010.csv")
df_2010 = df.rename(columns={'Isabella': 'name', '22924': 'total', 'F':'sex'})
df_2010

            name sex  total
0         Sophia   F  20646
1           Emma   F  17351
2         Olivia   F  17029
3            Ava   F  15436
4          Emily   F  14277
...          ...  ..    ...
34079    Zymaire   M      5
34080     Zyonne   M      5
34081  Zyquarius   M      5
34082      Zyran   M      5
34083      Zzyzx   M      5

[34084 rows x 3 columns]

## For 2011

In [28]:
read_file = pd.read_csv ('yob/yob2011.txt')
read_file.to_csv('yob/2011.csv', index=None)
df = pd.read_csv("yob/2011.csv")
df_2011 = df.rename(columns={'Sophia': 'name', '21850': 'total', 'F':'sex'})
df_2011

           name sex  total
0      Isabella   F  19919
1          Emma   F  18808
2        Olivia   F  17327
3           Ava   F  15506
4         Emily   F  14265
...         ...  ..    ...
33913     Zylar   M      5
33914     Zylas   M      5
33915     Zyran   M      5
33916   Zyshawn   M      5
33917  Zytavion   M      5

[33918 rows x 3 columns]

## For 2012

In [29]:
read_file = pd.read_csv ('yob/yob2012.txt')
read_file.to_csv('yob/2012.csv', index=None)
df = pd.read_csv("yob/2012.csv")
df_2012 = df.rename(columns={'Sophia': 'name', '22320': 'total', 'F':'sex'})
df_2012

            name sex  total
0           Emma   F  20954
1       Isabella   F  19113
2         Olivia   F  17320
3            Ava   F  15541
4          Emily   F  13657
...          ...  ..    ...
33755      Zylin   M      5
33756     Zymari   M      5
33757      Zyrin   M      5
33758      Zyrus   M      5
33759  Zytaevius   M      5

[33760 rows x 3 columns]

## For 2013

In [30]:
read_file = pd.read_csv ('yob/yob2013.txt')
read_file.to_csv('yob/2013.csv', index=None)
df = pd.read_csv("yob/2013.csv")
df_2013 = df.rename(columns={'Sophia': 'name', '21232': 'total', 'F':'sex'})
df_2013

           name sex  total
0          Emma   F  20950
1        Olivia   F  18439
2      Isabella   F  17654
3           Ava   F  15256
4           Mia   F  13157
...         ...  ..    ...
33298     Zyere   M      5
33299     Zylar   M      5
33300    Zymari   M      5
33301    Zymeer   M      5
33302     Zyree   M      5

[33303 rows x 3 columns]

## For 2014

In [31]:
read_file = pd.read_csv ('yob/yob2014.txt')
read_file.to_csv('yob/2014.csv', index=None)
df = pd.read_csv("yob/2014.csv")
df_2014 = df.rename(columns={'Emma': 'name', '20943': 'total', 'F':'sex'})
df_2014

           name sex  total
0        Olivia   F  19823
1        Sophia   F  18630
2      Isabella   F  17108
3           Ava   F  15709
4           Mia   F  13517
...         ...  ..    ...
33263    Zykeem   M      5
33264    Zymeer   M      5
33265   Zymiere   M      5
33266     Zyran   M      5
33267     Zyrin   M      5

[33268 rows x 3 columns]

## For 2015

In [32]:
read_file = pd.read_csv ('yob/yob2015.txt')
read_file.to_csv('yob/2015.csv', index=None)
df = pd.read_csv("yob/2015.csv")
df_2015 = df.rename(columns={'Emma': 'name', '20465': 'total', 'F':'sex'})
df_2015

           name sex  total
0        Olivia   F  19710
1        Sophia   F  17434
2           Ava   F  16386
3      Isabella   F  15636
4           Mia   F  14914
...         ...  ..    ...
33139    Zykell   M      5
33140    Zyking   M      5
33141     Zykir   M      5
33142     Zyrus   M      5
33143      Zyus   M      5

[33144 rows x 3 columns]

## For 2016

In [33]:
read_file = pd.read_csv ('yob/yob2016.txt')
read_file.to_csv('yob/2016.csv', index=None)
df = pd.read_csv("yob/2016.csv")
df_2016 = df.rename(columns={'Emma': 'name', '19522': 'total', 'F':'sex'})
df_2016

           name sex  total
0        Olivia   F  19380
1           Ava   F  16325
2        Sophia   F  16149
3      Isabella   F  14829
4           Mia   F  14442
...         ...  ..    ...
33025    Zolton   M      5
33026    Zurich   M      5
33027    Zyahir   M      5
33028      Zyel   M      5
33029     Zylyn   M      5

[33030 rows x 3 columns]

## For 2017

In [34]:
read_file = pd.read_csv ('yob/yob2017.txt')
read_file.to_csv('yob/2017.csv', index=None)
df = pd.read_csv("yob/2017.csv")
df_2017 = df.rename(columns={'Emma': 'name', '19837': 'total', 'F':'sex'})
df_2017

           name sex  total
0        Olivia   F  18744
1           Ava   F  15988
2      Isabella   F  15214
3        Sophia   F  14903
4           Mia   F  13494
...         ...  ..    ...
32628     Zykai   M      5
32629    Zykeem   M      5
32630     Zylin   M      5
32631     Zylis   M      5
32632     Zyrie   M      5

[32633 rows x 3 columns]

## For 2018

In [35]:
read_file = pd.read_csv ('yob/yob2018.txt')
read_file.to_csv('yob/2018.csv', index=None)
df = pd.read_csv("yob/2018.csv")
df_2018 = df.rename(columns={'Emma': 'name', '18770': 'total', 'F':'sex'})
df_2018

            name sex  total
0         Olivia   F  18011
1            Ava   F  14985
2       Isabella   F  14524
3         Sophia   F  13979
4      Charlotte   F  13005
...          ...  ..    ...
32172      Zylas   M      5
32173      Zyran   M      5
32174      Zyrie   M      5
32175      Zyron   M      5
32176      Zzyzx   M      5

[32177 rows x 3 columns]

## For 2019

In [36]:
read_file = pd.read_csv ('yob/yob2019.txt')
read_file.to_csv('yob/2019.csv', index=None)
df = pd.read_csv("yob/2019.csv")
df_2019 = df.rename(columns={'Olivia': 'name', '18508': 'total', 'F':'sex'})
df_2019

            name sex  total
0           Emma   F  17155
1            Ava   F  14474
2         Sophia   F  13753
3       Isabella   F  13344
4      Charlotte   F  13191
...          ...  ..    ...
32024     Zyheem   M      5
32025      Zykel   M      5
32026     Zyking   M      5
32027        Zyn   M      5
32028      Zyran   M      5

[32029 rows x 3 columns]

## Merge the Dataframes

Here I will merge all the data frames into a big one

In [37]:
df_names = pd.concat([df_2010, df_2011, df_2012, df_2013, df_2014, df_2015, df_2016, df_2017, df_2018, df_2019], ignore_index=True)

Now I will make sure to sort the values by total number of occurances

In [38]:
most_df = df_names.sort_values(by='total', ascending=False)
most_df

           name sex  total
19819     Jacob   M  22139
68002      Emma   F  20954
101762     Emma   F  20950
0        Sophia   F  20646
317264     Liam   M  20555
...         ...  ..    ...
153654    Ravya   F      5
153653  Rashiya   F      5
153652  Ranylah   F      5
153651    Ranna   F      5
331345    Zyran   M      5

[331346 rows x 3 columns]

In [39]:
grouped = most_df.groupby(['name']).agg('sum')
grouped = grouped.sort_values(by='total', ascending=False)
grouped.head(25)

            total
name
Noah       184255
Liam       173961
Olivia     165950
Jacob      163143
William    159881
Mason      158441
Ava        155745
Ethan      149073
Isabella   147530
Michael    145155
Alexander  142171
James      139845
Elijah     137029
Logan      134908
Benjamin   134455
Daniel     133873
Jayden     132061
Aiden      130078
Mia        129015
Matthew    125007
Abigail    118648
Lucas      118629
Emily      117617
David      116604
Jackson    116305

In [40]:
names = most_df.reset_index(drop=True, inplace=True)
names = most_df.sort_values(by=['sex', 'total'], ascending= False)
names

           name sex  total
0         Jacob   M  22139
4          Liam   M  20555
5         Jacob   M  20378
6          Liam   M  19924
10         Noah   M  19650
...         ...  ..    ...
331340     Raye   F      5
331341    Ravya   F      5
331342  Rashiya   F      5
331343  Ranylah   F      5
331344    Ranna   F      5

[331346 rows x 3 columns]

In [41]:
boy_names = names.head(2000)
boy_names

         name sex  total
0       Jacob   M  22139
4        Liam   M  20555
5       Jacob   M  20378
6        Liam   M  19924
10       Noah   M  19650
...       ...  ..    ...
3567   Travis   M   1941
3568    Jorge   M   1939
3569    Bryce   M   1939
3573     Paul   M   1937
3574  Ezekiel   M   1937

[2000 rows x 3 columns]

In [42]:
girls = most_df.sort_values(by=['sex', 'total'], ascending=[True, False])
girls

            name sex  total
1           Emma   F  20954
2           Emma   F  20950
3         Sophia   F  20646
7       Isabella   F  19919
8         Olivia   F  19823
...          ...  ..    ...
330454    Callin   M      5
330455   Calhoun   M      5
330456    Caleel   M      5
330457     Calab   M      5
331345     Zyran   M      5

[331346 rows x 3 columns]

In [43]:
girl_names = girls.head(2000)
girl_names

          name sex  total
1         Emma   F  20954
2         Emma   F  20950
3       Sophia   F  20646
7     Isabella   F  19919
8       Olivia   F  19823
...        ...  ..    ...
4339    Finley   F   1569
4343    Leslie   F   1565
4344    Eloise   F   1564
4346    Emilia   F   1563
4347   Giselle   F   1563

[2000 rows x 3 columns]

In [44]:
top_names = pd.concat([boy_names, girl_names], ignore_index=True)
top_names

         name sex  total
0       Jacob   M  22139
1        Liam   M  20555
2       Jacob   M  20378
3        Liam   M  19924
4        Noah   M  19650
...       ...  ..    ...
3995   Finley   F   1569
3996   Leslie   F   1565
3997   Eloise   F   1564
3998   Emilia   F   1563
3999  Giselle   F   1563

[4000 rows x 3 columns]

## Task 2: Create Features

### Features to create:
- Length of name (integer value)
- Total number of vowel (integer value)
- starts_with (a, b, c, d, etc.)
- ends_with(a, b, c, d, et.c)
- number of hard consonants ('p', 't', 'k', 'b', 'd', or 'g')

In [45]:
top_names["Name Length"]= top_names["name"].str.len()
top_names

         name sex  total  Name Length
0       Jacob   M  22139            5
1        Liam   M  20555            4
2       Jacob   M  20378            5
3        Liam   M  19924            4
4        Noah   M  19650            4
...       ...  ..    ...          ...
3995   Finley   F   1569            6
3996   Leslie   F   1565            6
3997   Eloise   F   1564            6
3998   Emilia   F   1563            6
3999  Giselle   F   1563            7

[4000 rows x 4 columns]

In [46]:
top_names['Vowel Count'] = top_names['name'].str.count('[aeiouAEIOU]')
top_names

         name sex  total  Name Length  Vowel Count
0       Jacob   M  22139            5            2
1        Liam   M  20555            4            2
2       Jacob   M  20378            5            2
3        Liam   M  19924            4            2
4        Noah   M  19650            4            2
...       ...  ..    ...          ...          ...
3995   Finley   F   1569            6            2
3996   Leslie   F   1565            6            3
3997   Eloise   F   1564            6            4
3998   Emilia   F   1563            6            4
3999  Giselle   F   1563            7            3

[4000 rows x 5 columns]

In [47]:
top_names['Starts With']= top_names['name'].astype(str).str[0]
top_names

         name sex  total  Name Length  Vowel Count Starts With
0       Jacob   M  22139            5            2           J
1        Liam   M  20555            4            2           L
2       Jacob   M  20378            5            2           J
3        Liam   M  19924            4            2           L
4        Noah   M  19650            4            2           N
...       ...  ..    ...          ...          ...         ...
3995   Finley   F   1569            6            2           F
3996   Leslie   F   1565            6            3           L
3997   Eloise   F   1564            6            4           E
3998   Emilia   F   1563            6            4           E
3999  Giselle   F   1563            7            3           G

[4000 rows x 6 columns]

In [48]:
top_names['Ends With']= top_names['name'].astype(str).str[-1]
top_names

         name sex  total  Name Length  Vowel Count Starts With Ends With
0       Jacob   M  22139            5            2           J         b
1        Liam   M  20555            4            2           L         m
2       Jacob   M  20378            5            2           J         b
3        Liam   M  19924            4            2           L         m
4        Noah   M  19650            4            2           N         h
...       ...  ..    ...          ...          ...         ...       ...
3995   Finley   F   1569            6            2           F         y
3996   Leslie   F   1565            6            3           L         e
3997   Eloise   F   1564            6            4           E         e
3998   Emilia   F   1563            6            4           E         a
3999  Giselle   F   1563            7            3           G         e

[4000 rows x 7 columns]

In [49]:
top_names['Consonants Count'] = top_names['name'].str.count('[qwrtypsdfghjklzxcvbnmQWRTYPSDFGHJKLZXCVBNM]')
top_names

,name,sex,total,Name Length,Vowel Count,Starts With,Ends With,Consonants Count
0,Jacob,M,22139,5,2,J,b,3
1,Liam,M,20555,4,2,L,m,2
2,Jacob,M,20378,5,2,J,b,3
3,Liam,M,19924,4,2,L,m,2
4,Noah,M,19650,4,2,N,h,2
...,...,...,...,...,...,...,...,...
3995,Finley,F,1569,6,2,F,y,4
3996,Leslie,F,1565,6,3,L,e,3
3997,Eloise,F,1564,6,4,E,e,2
3998,Emilia,F,1563,6,4,E,a,2
3999,Giselle,F,1563,7,3,G,e,4

In [50]:
dfNames = top_names.iloc[:, [0,1,2]]
dfNames

         name sex  total
0       Jacob   M  22139
1        Liam   M  20555
2       Jacob   M  20378
3        Liam   M  19924
4        Noah   M  19650
...       ...  ..    ...
3995   Finley   F   1569
3996   Leslie   F   1565
3997   Eloise   F   1564
3998   Emilia   F   1563
3999  Giselle   F   1563

[4000 rows x 3 columns]

In [51]:
for_dict = top_names.iloc[:, [3,4,5,6,7]]
for_dict

      Name Length  Vowel Count Starts With Ends With  Consonants Count
0               5            2           J         b                 3
1               4            2           L         m                 2
2               5            2           J         b                 3
3               4            2           L         m                 2
4               4            2           N         h                 2
...           ...          ...         ...       ...               ...
3995            6            2           F         y                 4
3996            6            3           L         e                 3
3997            6            4           E         e                 2
3998            6            4           E         a                 2
3999            7            3           G         e                 4

[4000 rows x 5 columns]

In [52]:
for_dict.to_dict('record')

[{'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 'b',
  'Consonants Count': 3},
 {'Name Length': 4,
  'Vowel Count': 2,
  'Starts With': 'L',
  'Ends With': 'm',
  'Consonants Count': 2},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 'b',
  'Consonants Count': 3},
 {'Name Length': 4,
  'Vowel Count': 2,
  'Starts With': 'L',
  'Ends With': 'm',
  'Consonants Count': 2},
 {'Name Length': 4,
  'Vowel Count': 2,
  'Starts With': 'N',
  'Ends With': 'h',
  'Consonants Count': 2},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'M',
  'Ends With': 'n',
  'Consonants Count': 3},
 {'Name Length': 4,
  'Vowel Count': 2,
  'Starts With': 'N',
  'Ends With': 'h',
  'Consonants Count': 2},
 {'Name Length': 4,
  'Vowel Count': 2,
  'Starts With': 'N',
  'Ends With': 'h',
  'Consonants Count': 2},
 {'Name Length': 4,
  'Vowel Count': 2,
  'Starts With': 'N',
  'Ends With': 'h',
  'Consonants Count': 2},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 'b',
  'Consonants Count': 3},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'M',
  'Ends With': 'n',
  'Consonants Count': 3},
 {'Name Length': 4,
  'Vowel Count': 2,
  'Starts With': 'L',
  'Ends With': 'm',
  'Consonants Count': 2},
 {'Name Length': 4,
  'Vowel Count': 2,
  'Starts With': 'L',
  'Ends With': 'm',
  'Consonants Count': 2},
 {'Name Length': 4,
  'Vowel Count': 2,
  'Starts With': 'N',
  'Ends With': 'h',
  'Consonants Count': 2},
 {'Name Length': 4,
  'Vowel Count': 2,
  'Starts With': 'L',
  'Ends With': 'm',
  'Consonants Count': 2},
 {'Name Length': 4,
  'Vowel Count': 2,
  'Starts With': 'N',
  'Ends With': 'h',
  'Consonants Count': 2},
 {'Name Length': 4,
  'Vowel Count': 2,
  'Starts With': 'N',
  'Ends With': 'h',
  'Consonants Count': 2},
 {'Name Length': 4,
  'Vowel Count': 2,
  'Starts With': 'L',
  'Ends With': 'm',
  'Consonants Count': 2},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 'b',
  'Consonants Count': 3},
 {'Name Length': 4,
  'Vowel Count': 2,
  'Starts With': 'L',
  'Ends With': 'm',
  'Consonants Count': 2},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'E',
  'Ends With': 'n',
  'Consonants Count': 3},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'M',
  'Ends With': 'n',
  'Consonants Count': 3},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'E',
  'Ends With': 'n',
  'Consonants Count': 3},
 {'Name Length': 7,
  'Vowel Count': 3,
  'Starts With': 'M',
  'Ends With': 'l',
  'Consonants Count': 4},
 {'Name Length': 4,
  'Vowel Count': 2,
  'Starts With': 'N',
  'Ends With': 'h',
  'Consonants Count': 2},
 {'Name Length': 7,
  'Vowel Count': 3,
  'Starts With': 'W',
  'Ends With': 'm',
  'Consonants Count': 4},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'M',
  'Ends With': 'n',
  'Consonants Count': 3},
 {'Name Length': 6,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 'n',
  'Consonants Count': 4},
 {'Name Length': 7,
  'Vowel Count': 3,
  'Starts With': 'W',
  'Ends With': 'm',
  'Consonants Count': 4},
 {'Name Length': 6,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 'n',
  'Consonants Count': 4},
 {'Name Length': 7,
  'Vowel Count': 3,
  'Starts With': 'W',
  'Ends With': 'm',
  'Consonants Count': 4},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 'b',
  'Consonants Count': 3},
 {'Name Length': 4,
  'Vowel Count': 2,
  'Starts With': 'N',
  'Ends With': 'h',
  'Consonants Count': 2},
 {'Name Length': 7,
  'Vowel Count': 3,
  'Starts With': 'W',
  'Ends With': 'm',
  'Consonants Count': 4},
 {'Name Length': 4,
  'Vowel Count': 2,
  'Starts With': 'L',
  'Ends With': 'm',
  'Consonants Count': 2},
 {'Name Length': 7,
  'Vowel Count': 3,
  'Starts With': 'M',
  'Ends With': 'l',
  'Consonants Count': 4},
 {'Name Length': 9,
  'Vowel Count': 4,
  'Starts With': 'A',
  'Ends With': 'r',
  'Consonants Count': 5},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'E',
  'Ends With': 'n',
  'Consonants Count': 3},
 {'Name Length': 7,
  'Vowel Count': 3,
  'Starts With': 'W',
  'Ends With': 'm',
  'Consonants Count': 4},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'M',
  'Ends With': 'n',
  'Consonants Count': 3},
 {'Name Length': 4,
  'Vowel Count': 2,
  'Starts With': 'N',
  'Ends With': 'h',
  'Consonants Count': 2},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'E',
  'Ends With': 'n',
  'Consonants Count': 3},
 {'Name Length': 7,
  'Vowel Count': 3,
  'Starts With': 'M',
  'Ends With': 'l',
  'Consonants Count': 4},
 {'Name Length': 6,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 'n',
  'Consonants Count': 4},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 'b',
  'Consonants Count': 3},
 {'Name Length': 7,
  'Vowel Count': 3,
  'Starts With': 'W',
  'Ends With': 'm',
  'Consonants Count': 4},
 {'Name Length': 6,
  'Vowel Count': 3,
  'Starts With': 'D',
  'Ends With': 'l',
  'Consonants Count': 3},
 {'Name Length': 7,
  'Vowel Count': 3,
  'Starts With': 'W',
  'Ends With': 'm',
  'Consonants Count': 4},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'E',
  'Ends With': 'n',
  'Consonants Count': 3},
 {'Name Length': 9,
  'Vowel Count': 4,
  'Starts With': 'A',
  'Ends With': 'r',
  'Consonants Count': 5},
 {'Name Length': 5,
  'Vowel Count': 3,
  'Starts With': 'A',
  'Ends With': 'n',
  'Consonants Count': 2},
 {'Name Length': 7,
  'Vowel Count': 3,
  'Starts With': 'M',
  'Ends With': 'l',
  'Consonants Count': 4},
 {'Name Length': 5,
  'Vowel Count': 3,
  'Starts With': 'A',
  'Ends With': 'n',
  'Consonants Count': 2},
 {'Name Length': 7,
  'Vowel Count': 2,
  'Starts With': 'A',
  'Ends With': 'y',
  'Consonants Count': 5},
 {'Name Length': 7,
  'Vowel Count': 3,
  'Starts With': 'M',
  'Ends With': 'l',
  'Consonants Count': 4},
 {'Name Length': 6,
  'Vowel Count': 3,
  'Starts With': 'J',
  'Ends With': 'a',
  'Consonants Count': 3},
 {'Name Length': 9,
  'Vowel Count': 4,
  'Starts With': 'A',
  'Ends With': 'r',
  'Consonants Count': 5},
 {'Name Length': 6,
  'Vowel Count': 3,
  'Starts With': 'D',
  'Ends With': 'l',
  'Consonants Count': 3},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'M',
  'Ends With': 'n',
  'Consonants Count': 3},
 {'Name Length': 9,
  'Vowel Count': 4,
  'Starts With': 'A',
  'Ends With': 'r',
  'Consonants Count': 5},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'E',
  'Ends With': 'n',
  'Consonants Count': 3},
 {'Name Length': 7,
  'Vowel Count': 3,
  'Starts With': 'W',
  'Ends With': 'm',
  'Consonants Count': 4},
 {'Name Length': 5,
  'Vowel Count': 3,
  'Starts With': 'A',
  'Ends With': 'n',
  'Consonants Count': 2},
 {'Name Length': 9,
  'Vowel Count': 4,
  'Starts With': 'A',
  'Ends With': 'r',
  'Consonants Count': 5},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 's',
  'Consonants Count': 3},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'M',
  'Ends With': 'n',
  'Consonants Count': 3},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 's',
  'Consonants Count': 3},
 {'Name Length': 6,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 'n',
  'Consonants Count': 4},
 {'Name Length': 8,
  'Vowel Count': 3,
  'Starts With': 'B',
  'Ends With': 'n',
  'Consonants Count': 5},
 {'Name Length': 7,
  'Vowel Count': 3,
  'Starts With': 'W',
  'Ends With': 'm',
  'Consonants Count': 4},
 {'Name Length': 9,
  'Vowel Count': 4,
  'Starts With': 'A',
  'Ends With': 'r',
  'Consonants Count': 5},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 'b',
  'Consonants Count': 3},
 {'Name Length': 7,
  'Vowel Count': 3,
  'Starts With': 'M',
  'Ends With': 'l',
  'Consonants Count': 4},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 's',
  'Consonants Count': 3},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 's',
  'Consonants Count': 3},
 {'Name Length': 6,
  'Vowel Count': 3,
  'Starts With': 'D',
  'Ends With': 'l',
  'Consonants Count': 3},
 {'Name Length': 6,
  'Vowel Count': 3,
  'Starts With': 'D',
  'Ends With': 'l',
  'Consonants Count': 3},
 {'Name Length': 11,
  'Vowel Count': 3,
  'Starts With': 'C',
  'Ends With': 'r',
  'Consonants Count': 8},
 {'Name Length': 7,
  'Vowel Count': 2,
  'Starts With': 'A',
  'Ends With': 'y',
  'Consonants Count': 5},
 {'Name Length': 6,
  'Vowel Count': 2,
  'Starts With': 'A',
  'Ends With': 'w',
  'Consonants Count': 4},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'D',
  'Ends With': 'd',
  'Consonants Count': 3},
 {'Name Length': 7,
  'Vowel Count': 2,
  'Starts With': 'M',
  'Ends With': 'w',
  'Consonants Count': 5},
 {'Name Length': 7,
  'Vowel Count': 2,
  'Starts With': 'M',
  'Ends With': 'w',
  'Consonants Count': 5},
 {'Name Length': 7,
  'Vowel Count': 3,
  'Starts With': 'M',
  'Ends With': 'l',
  'Consonants Count': 4},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'L',
  'Ends With': 'n',
  'Consonants Count': 3},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'L',
  'Ends With': 'n',
  'Consonants Count': 3},
 {'Name Length': 7,
  'Vowel Count': 2,
  'Starts With': 'M',
  'Ends With': 'w',
  'Consonants Count': 5},
 {'Name Length': 6,
  'Vowel Count': 3,
  'Starts With': 'E',
  'Ends With': 'h',
  'Consonants Count': 3},
 {'Name Length': 6,
  'Vowel Count': 3,
  'Starts With': 'D',
  'Ends With': 'l',
  'Consonants Count': 3},
 {'Name Length': 6,
  'Vowel Count': 3,
  'Starts With': 'E',
  'Ends With': 'h',
  'Consonants Count': 3},
 {'Name Length': 6,
  'Vowel Count': 3,
  'Starts With': 'O',
  'Ends With': 'r',
  'Consonants Count': 3},
 {'Name Length': 6,
  'Vowel Count': 3,
  'Starts With': 'E',
  'Ends With': 'h',
  'Consonants Count': 3},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 's',
  'Consonants Count': 3},
 {'Name Length': 6,
  'Vowel Count': 3,
  'Starts With': 'E',
  'Ends With': 'h',
  'Consonants Count': 3},
 {'Name Length': 6,
  'Vowel Count': 3,
  'Starts With': 'E',
  'Ends With': 'h',
  'Consonants Count': 3},
 {'Name Length': 6,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 'h',
  'Consonants Count': 4},
 {'Name Length': 8,
  'Vowel Count': 3,
  'Starts With': 'B',
  'Ends With': 'n',
  'Consonants Count': 5},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'E',
  'Ends With': 'n',
  'Consonants Count': 3},
 {'Name Length': 8,
  'Vowel Count': 3,
  'Starts With': 'B',
  'Ends With': 'n',
  'Consonants Count': 5},
 {'Name Length': 6,
  'Vowel Count': 3,
  'Starts With': 'E',
  'Ends With': 'h',
  'Consonants Count': 3},
 {'Name Length': 6,
  'Vowel Count': 3,
  'Starts With': 'J',
  'Ends With': 'a',
  'Consonants Count': 3},
 {'Name Length': 8,
  'Vowel Count': 3,
  'Starts With': 'B',
  'Ends With': 'n',
  'Consonants Count': 5},
 {'Name Length': 6,
  'Vowel Count': 3,
  'Starts With': 'E',
  'Ends With': 'h',
  'Consonants Count': 3},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'L',
  'Ends With': 'n',
  'Consonants Count': 3},
 {'Name Length': 5,
  'Vowel Count': 3,
  'Starts With': 'A',
  'Ends With': 'n',
  'Consonants Count': 2},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 's',
  'Consonants Count': 3},
 {'Name Length': 7,
  'Vowel Count': 3,
  'Starts With': 'W',
  'Ends With': 'm',
  'Consonants Count': 4},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 's',
  'Consonants Count': 3},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'M',
  'Ends With': 'n',
  'Consonants Count': 3},
 {'Name Length': 6,
  'Vowel Count': 3,
  'Starts With': 'D',
  'Ends With': 'l',
  'Consonants Count': 3},
 {'Name Length': 8,
  'Vowel Count': 3,
  'Starts With': 'B',
  'Ends With': 'n',
  'Consonants Count': 5},
 {'Name Length': 5,
  'Vowel Count': 3,
  'Starts With': 'A',
  'Ends With': 'n',
  'Consonants Count': 2},
 {'Name Length': 6,
  'Vowel Count': 3,
  'Starts With': 'O',
  'Ends With': 'r',
  'Consonants Count': 3},
 {'Name Length': 8,
  'Vowel Count': 3,
  'Starts With': 'B',
  'Ends With': 'n',
  'Consonants Count': 5},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 's',
  'Consonants Count': 3},
 {'Name Length': 4,
  'Vowel Count': 2,
  'Starts With': 'L',
  'Ends With': 'm',
  'Consonants Count': 2},
 {'Name Length': 9,
  'Vowel Count': 4,
  'Starts With': 'A',
  'Ends With': 'r',
  'Consonants Count': 5},
 {'Name Length': 5,
  'Vowel Count': 3,
  'Starts With': 'A',
  'Ends With': 'n',
  'Consonants Count': 2},
 {'Name Length': 6,
  'Vowel Count': 3,
  'Starts With': 'E',
  'Ends With': 'h',
  'Consonants Count': 3},
 {'Name Length': 7,
  'Vowel Count': 2,
  'Starts With': 'M',
  'Ends With': 'w',
  'Consonants Count': 5},
 {'Name Length': 6,
  'Vowel Count': 3,
  'Starts With': 'E',
  'Ends With': 'h',
  'Consonants Count': 3},
 {'Name Length': 6,
  'Vowel Count': 2,
  'Starts With': 'A',
  'Ends With': 'w',
  'Consonants Count': 4},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 's',
  'Consonants Count': 3},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'D',
  'Ends With': 'd',
  'Consonants Count': 3},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 'b',
  'Consonants Count': 3},
 {'Name Length': 6,
  'Vowel Count': 3,
  'Starts With': 'O',
  'Ends With': 'r',
  'Consonants Count': 3},
 {'Name Length': 7,
  'Vowel Count': 2,
  'Starts With': 'A',
  'Ends With': 'y',
  'Consonants Count': 5},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 's',
  'Consonants Count': 3},
 {'Name Length': 8,
  'Vowel Count': 3,
  'Starts With': 'B',
  'Ends With': 'n',
  'Consonants Count': 5},
 {'Name Length': 6,
  'Vowel Count': 3,
  'Starts With': 'O',
  'Ends With': 'r',
  'Consonants Count': 3},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'L',
  'Ends With': 's',
  'Consonants Count': 3},
 {'Name Length': 11,
  'Vowel Count': 3,
  'Starts With': 'C',
  'Ends With': 'r',
  'Consonants Count': 8},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'L',
  'Ends With': 'n',
  'Consonants Count': 3},
 {'Name Length': 8,
  'Vowel Count': 3,
  'Starts With': 'B',
  'Ends With': 'n',
  'Consonants Count': 5},
 {'Name Length': 6,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 'n',
  'Consonants Count': 4},
 {'Name Length': 6,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 'h',
  'Consonants Count': 4},
 {'Name Length': 6,
  'Vowel Count': 3,
  'Starts With': 'D',
  'Ends With': 'l',
  'Consonants Count': 3},
 {'Name Length': 6,
  'Vowel Count': 3,
  'Starts With': 'E',
  'Ends With': 'h',
  'Consonants Count': 3},
 {'Name Length': 7,
  'Vowel Count': 2,
  'Starts With': 'M',
  'Ends With': 'w',
  'Consonants Count': 5},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'L',
  'Ends With': 'n',
  'Consonants Count': 3},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'L',
  'Ends With': 's',
  'Consonants Count': 3},
 {'Name Length': 7,
  'Vowel Count': 3,
  'Starts With': 'G',
  'Ends With': 'l',
  'Consonants Count': 4},
 {'Name Length': 8,
  'Vowel Count': 3,
  'Starts With': 'B',
  'Ends With': 'n',
  'Consonants Count': 5},
 {'Name Length': 7,
  'Vowel Count': 2,
  'Starts With': 'M',
  'Ends With': 'w',
  'Consonants Count': 5},
 {'Name Length': 7,
  'Vowel Count': 3,
  'Starts With': 'M',
  'Ends With': 'l',
  'Consonants Count': 4},
 {'Name Length': 6,
  'Vowel Count': 3,
  'Starts With': 'J',
  'Ends With': 'a',
  'Consonants Count': 3},
 {'Name Length': 7,
  'Vowel Count': 2,
  'Starts With': 'M',
  'Ends With': 'w',
  'Consonants Count': 5},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'L',
  'Ends With': 's',
  'Consonants Count': 3},
 {'Name Length': 6,
  'Vowel Count': 2,
  'Starts With': 'A',
  'Ends With': 'w',
  'Consonants Count': 4},
 {'Name Length': 7,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 'n',
  'Consonants Count': 5},
 {'Name Length': 6,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 'h',
  'Consonants Count': 4},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'D',
  'Ends With': 'd',
  'Consonants Count': 3},
 {'Name Length': 9,
  'Vowel Count': 4,
  'Starts With': 'A',
  'Ends With': 'r',
  'Consonants Count': 5},
 {'Name Length': 7,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 'n',
  'Consonants Count': 5},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'M',
  'Ends With': 'n',
  'Consonants Count': 3},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'L',
  'Ends With': 'n',
  'Consonants Count': 3},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'E',
  'Ends With': 'n',
  'Consonants Count': 3},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'L',
  'Ends With': 's',
  'Consonants Count': 3},
 {'Name Length': 8,
  'Vowel Count': 3,
  'Starts With': 'B',
  'Ends With': 'n',
  'Consonants Count': 5},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'L',
  'Ends With': 'n',
  'Consonants Count': 3},
 {'Name Length': 7,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 'n',
  'Consonants Count': 5},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'D',
  'Ends With': 'd',
  'Consonants Count': 3},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'L',
  'Ends With': 'n',
  'Consonants Count': 3},
 {'Name Length': 7,
  'Vowel Count': 3,
  'Starts With': 'G',
  'Ends With': 'l',
  'Consonants Count': 4},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'L',
  'Ends With': 's',
  'Consonants Count': 3},
 {'Name Length': 7,
  'Vowel Count': 2,
  'Starts With': 'A',
  'Ends With': 'y',
  'Consonants Count': 5},
 {'Name Length': 7,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 'n',
  'Consonants Count': 5},
 {'Name Length': 6,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 'h',
  'Consonants Count': 4},
 {'Name Length': 5,
  'Vowel Count': 3,
  'Starts With': 'A',
  'Ends With': 'n',
  'Consonants Count': 2},
 {'Name Length': 7,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 'n',
  'Consonants Count': 5},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'D',
  'Ends With': 'd',
  'Consonants Count': 3},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'L',
  'Ends With': 's',
  'Consonants Count': 3},
 {'Name Length': 6,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 'h',
  'Consonants Count': 4},
 {'Name Length': 9,
  'Vowel Count': 4,
  'Starts With': 'A',
  'Ends With': 'r',
  'Consonants Count': 5},
 {'Name Length': 4,
  'Vowel Count': 1,
  'Starts With': 'R',
  'Ends With': 'n',
  'Consonants Count': 3},
 {'Name Length': 6,
  'Vowel Count': 3,
  'Starts With': 'S',
  'Ends With': 'l',
  'Consonants Count': 3},
 {'Name Length': 11,
  'Vowel Count': 3,
  'Starts With': 'C',
  'Ends With': 'r',
  'Consonants Count': 8},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'E',
  'Ends With': 'n',
  'Consonants Count': 3},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 'b',
  'Consonants Count': 3},
 {'Name Length': 6,
  'Vowel Count': 3,
  'Starts With': 'J',
  'Ends With': 'a',
  'Consonants Count': 3},
 {'Name Length': 7,
  'Vowel Count': 2,
  'Starts With': 'J',
  'Ends With': 'n',
  'Consonants Count': 5},
 {'Name Length': 5,
  'Vowel Count': 2,
  'Starts With': 'D',
  'Ends With': 'd',
  'Consonants Count': 3},
 {'Name Length': 6,
  'Vowel Count': 3,
  'Starts With': 'D',
  'Ends With': 'l',
  'Consonants Count': 3},
 {'Name Length': 7,
  'Vowel Count': 3,
  'Starts With': 'M',
  'Ends With': 'l',
  'Consonants Count': 4},
 {'Name Length': 7,
  'Vowel Count': 2,
  'Starts With': 'M',
  'Ends With': 'w',
  'Consonants Count': 5},

In [53]:
from sklearn.feature_extraction import DictVectorizer
vec = DictVectorizer(sparse=False, dtype= int)
vec.fit_transform(for_dict.to_dict('record'))

array([[3, 0, 1, ..., 0, 0, 2],
       [2, 0, 0, ..., 0, 0, 2],
       [3, 0, 1, ..., 0, 0, 2],
       ...,
       [2, 0, 0, ..., 0, 0, 4],
       [2, 1, 0, ..., 0, 0, 4],
       [4, 0, 0, ..., 0, 0, 3]])

In [54]:
vec = DictVectorizer(sparse=True, dtype=int)
x = vec.fit_transform(for_dict.to_dict('record'))
x

<4000x47 sparse matrix of type '<class 'numpy.int64'>'
	with 20000 stored elements in Compressed Sparse Row format>

In [55]:
things = vec.get_feature_names()
things

['Consonants Count',
 'Ends With=a',
 'Ends With=b',
 'Ends With=c',
 'Ends With=d',
 'Ends With=e',
 'Ends With=g',
 'Ends With=h',
 'Ends With=i',
 'Ends With=k',
 'Ends With=l',
 'Ends With=m',
 'Ends With=n',
 'Ends With=o',
 'Ends With=r',
 'Ends With=s',
 'Ends With=t',
 'Ends With=u',
 'Ends With=w',
 'Ends With=x',
 'Ends With=y',
 'Name Length',
 'Starts With=A',
 'Starts With=B',
 'Starts With=C',
 'Starts With=D',
 'Starts With=E',
 'Starts With=F',
 'Starts With=G',
 'Starts With=H',
 'Starts With=I',
 'Starts With=J',
 'Starts With=K',
 'Starts With=L',
 'Starts With=M',
 'Starts With=N',
 'Starts With=O',
 'Starts With=P',
 'Starts With=Q',
 'Starts With=R',
 'Starts With=S',
 'Starts With=T',
 'Starts With=V',
 'Starts With=W',
 'Starts With=X',
 'Starts With=Z',
 'Vowel Count']

In [56]:
dfTrain = pd.DataFrame(x.toarray(), columns=things)
dfTrain

,Consonants Count,Ends With=a,Ends With=b,Ends With=c,Ends With=d,Ends With=e,Ends With=g,Ends With=h,Ends With=i,Ends With=k,...,Starts With=P,Starts With=Q,Starts With=R,Starts With=S,Starts With=T,Starts With=V,Starts With=W,Starts With=X,Starts With=Z,Vowel Count
0,3,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
1,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
2,3,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
3,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
4,2,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
3996,3,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
3997,2,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4
3998,2,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4
3999,4,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3

In [90]:
dfclass = top_names.loc[:,:'sex']
dfclass.shape

(4000, 2)

In [93]:
dfclass

         name sex
0       Jacob   M
1        Liam   M
2       Jacob   M
3        Liam   M
4        Noah   M
...       ...  ..
3995   Finley   F
3996   Leslie   F
3997   Eloise   F
3998   Emilia   F
3999  Giselle   F

[4000 rows x 2 columns]

In [57]:
float_col = df.select_dtypes(include=['float64'])
for col in float_col.columns.values:
    df[col] = dfTrain[col].astype('int64')
print(dfTrain)

      Consonants Count  Ends With=a  Ends With=b  Ends With=c  Ends With=d  \
0                    3            0            1            0            0
1                    2            0            0            0            0
2                    3            0            1            0            0
3                    2            0            0            0            0
4                    2            0            0            0            0
...                ...          ...          ...          ...          ...
3995                 4            0            0            0            0
3996                 3            0            0            0            0
3997                 2            0            0            0            0
3998                 2            1            0            0            0
3999                 4            0            0            0            0

      Ends With=e  Ends With=g  Ends With=h  Ends With=i  Ends With=k  ...  \
0               0            0            0            0            0  ...
1               0            0            0            0            0  ...
2               0            0            0            0            0  ...
3               0            0            0            0            0  ...
4               0            0            1            0            0  ...
...           ...          ...          ...          ...          ...  ...
3995            0            0            0            0            0  ...
3996            1            0            0            0            0  ...
3997            1            0            0            0            0  ...
3998            0            0            0            0            0  ...
3999            1            0            0            0            0  ...

      Starts With=P  Starts With=Q  Starts With=R  Starts With=S  \
0                 0              0              0              0
1                 0              0              0              0
2                 0              0              0              0
3                 0              0              0              0
4                 0              0              0              0
...             ...            ...            ...            ...
3995              0              0              0              0
3996              0              0              0              0
3997              0              0              0              0
3998              0              0              0              0
3999              0              0              0              0

      Starts With=T  Starts With=V  Starts With=W  Starts With=X  \
0                 0              0              0              0
1                 0              0              0              0
2                 0              0              0              0
3                 0              0              0              0
4                 0              0              0              0
...             ...            ...            ...            ...
3995              0              0              0              0
3996              0              0              0              0
3997              0              0              0              0
3998              0              0              0              0
3999              0              0              0              0

      Starts With=Z  Vowel Count
0                 0            2
1                 0            2
2                 0            2
3                 0            2
4                 0            2
...             ...          ...
3995              0            2
3996              0            3
3997              0            4
3998              0            4
3999              0            3

[4000 rows x 47 columns]

## Task 3: Distance/Similarity Metrics

Write two functions, based on the formulas provided in class:

In [6]:
import numpy as np
from math import sqrt

In [68]:
def euclidean_distance(v1, v2):
    v1_array = np.array(v1) 
    v2_array = np.array(v2)
    return np.sqrt(np.sum(np.square(v1_array - v2_array)))

In [69]:
euclidean_distance([3,4,2,1], [1,1,1,1])

3.7416573867739413

In [70]:
import math

In [71]:
def cosine_similarity(v1,v2):
    sumxx, sumxy, sumyy = 0, 0, 0
    for i in range(len(v1)):
        x = v1[i]; y = v2[i]
        sumxx += x*x
        sumyy += y*y
        sumxy += x*y
    return sumxy/math.sqrt(sumxx*sumyy)

In [72]:
v1,v2 = [3, 45, 7, 2], [2, 54, 13, 15]
print(cosine_similarity(v1,v2))

0.97228425171235

In [73]:
dataset = [[2.7810836,2.550537003,0],
[1.465489372,2.362125076,0],
[3.396561688,4.400293529,0],
[1.38807019,1.850220317,0],
[3.06407232,3.005305973,0],
[7.627531214,2.759262235,1],
[5.332441248,2.088626775,1],
[6.922596716,1.77106367,1],
[8.675418651,-0.242068655,1],
[7.673756466,3.508563011,1]]
row0 = dataset[0]
for row in dataset:
    distance = euclidean_distance(row0, row)
    print(distance)

0.0
1.3290173915275787
1.9494646655653247
1.5591439385540549
0.5356280721938492
4.952940611164215
2.7789902674782985
4.3312480380207
6.59862349695304
5.084885603993178

## Task 4: Implement the kNN algorithm

`findNearestNeighbors` takes four parameters: one vector, one dataframe with instances (not including the vector that is the first parameter), the metric name (‘euclidean’ or ‘cosine’), and k (number of neighbors). After having calculated the distances between the given vector and every vector in the dataframe, it sorts them based on the meaning of the metric (for euclidean distance, we want the instances with the smallest distance; for the cosine similarity, we want the instances with the highest similarity). It finally returns the indices of the k nearest neighbors. For the purposes of this task, you should implement this function yourself and not use any library functions that do this work for you. In future assignments you can use library functions.

In [80]:
def get_neighbors(v1, dfTrain, k, metric):
    metricDict = {'euclidean': euclidean_distance,
                  'cosine': cosine_similarity
                 }
    
    distancesLst = []
    for i, row in dfTrain.iterrows(): 
        f = metricDict[metric]        
        dist = f(v1, row)
        
        distancesLst.append((dist, i)) 
    
   
    reverse = True if metric=='cosine' else False
    distancesLst.sort(reverse=reverse)
    

    indices = [el[1] for el in distancesLst]
    return indices[:k]

In [82]:
v1 = dfTrain.loc[0]
dfTrain = dfTrain.drop(0)

get_neighbors(v1, dfTrain, 11, 'euclidean')

[2, 9, 18, 31, 44, 71, 124, 178, 222, 64, 66]

`predictLabel` takes two parameters: one dataframe that contains the labels,  and the list of indices returned by findNearestNeighbors. The function returns the predicted label based on the majority vote of the instances represented by their indices.

In [94]:
def predictLabel(labelsDF, indices):
    neighbors = labelsDF[labelsDF.index.isin(indices)]
    return neighbors['sex'].mode()[0]

In [96]:
nearestIndices = [1, 100, 500, 2000, 2010] 

predictLabel(dfclass, nearestIndices)

'M'

In [98]:
indices = get_neighbors(v1, dfTrain, 11, 'cosine')
predictLabel(dfclass, indices)

'M'